index:
    path: /
    controller: App\Action\IndexAction

test:
    path: /test
    controller: App\Controller\DefaultController::index

user_register:
    path: /register
    controller: App\User\Register\UserRegisterAction
